version: '3.4'

services:
  prosperitopia-web:
    image: prosperitopia-web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4200:80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
